### PR TITLE
Add blogdown post

### PR DESCRIPTION
**Pull request by lorenzwalthert**

### CODE REVIEW

**Comment by maelle** [comment]
I don't understand why having to build the markdown by hand means you couldn't use GitHub pages? My own old website was Rmd+md https://github.com/maelle/oldsite but even if I had posted a md done by hand in the _posts folder I could still have used GitHub pages? Other than that you make a good case for the switch.

**Comment by maelle** [comment]
huog -> hugo

**Comment by maelle** [comment]
Speaking of Google Analytics https://support.pipdig.co/articles/gdpr-for-bloggers/

**Comment by maelle** [comment]
very nice to learn about .Rmarkdown!

**Comment by maelle** [comment]
Regarding deployment look at what Kirill &co are doing in https://github.com/ropenscilabs/tic , there's a blogdown example (I only looked at the bookdown example) and in https://github.com/ropenscilabs/travis there's a `use_travis_deploy` function to set up the keys automatically in GitHub and Travis.

**Comment by maelle** [comment]
.traivs.yml -> .travis.yml

**Comment by maelle** [comment]
last comment, maybe a flowchart would be useful?

**Comment by lorenzwalthert** [comment]
Thanks so much @maelle :-) Collaborative work rocks, although it means that I probably won't publish this soon because I should probably look into `tic` / `use_travis_deploy` first. I kind of hope / but don't hope at the same time that some of the work I did becomes redundant then :-)

**Comment by lorenzwalthert** [comment]
I will address your comments later in detail.

**Comment by maelle** [comment]
Well on the bright side you'll probably give super useful input for `tic` and `travis` docs&functionality. 😸

**Comment by lorenzwalthert** [comment]
> I don't understand why having to build the markdown by hand means you couldn't use GitHub pages? My own old website was Rmd+md https://github.com/maelle/oldsite but even if I had posted a md done by hand in the _posts folder I could still have used GitHub pages? Other than that you make a good case for the switch.

No I meant I could use GitHub pages but I had to build locally: 
> [...] I could not use automated builds on GitHub Pages.

**Comment by lorenzwalthert** [comment]
> Regarding deployment look at what Kirill &co are doing in https://github.com/ropenscilabs/tic , there's a blogdown example (I only looked at the bookdown example) and in https://github.com/ropenscilabs/travis there's a use_travis_deploy function to set up the keys automatically in GitHub and Travis.

Thanks for this one. I just forked the blogdown example and created a post on a devel branch and pushed a new blog post without html derivatives. Let's see how that compares to my approach.

**Comment by maelle** [comment]
I will be interested in your comparison 🤓

**Comment by lorenzwalthert** [comment]
Merging that for now, need to test if it works at all as expected 😊

**Pull request merged**
